- name: Install android-studio
  aur:
    packages:
    - android-studio

- name: Install android-tools
  pacman:
    packages:
    - android-tools

- name: Add primary user to adbusers groups
  user:
    user: "{{ username }}"
    groups:
    # - flutterusers
    - adbusers
