- name: Install dunst notifications
  pacman:
    packages: dunst

- name: Create dunst config directory
  directory:
    path: "/home/{{ username }}/.config/dunst"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Configure dunst
  template:
    src: files/dunstrc
    dest: "/home/{{ username }}/.config/dunst/dunstrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
