- name: Install GTK themes (AUR)
  aur:
    packages:
    - gnome-themes-extra

- name: Create gtk config directory
  directory:
    path: "/home/{{ username }}/.config/gtk-3.0"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Configure GTK themes
  template:
    src: files/gtk.ini
    dest: "/home/{{ username }}/.config/gtk-3.0/settings.ini"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

