- name: Install window manager and extras
  pacman:
    packages:
    - i3-wm
    - autorandr
    - xautolock
    - noto-fonts
    - lxappearance
    - feh

- name: Install window manager extras (AUR)
  aur:
    packages:
    - light-git
    - polybar
    - picom-git

- name: Copy wallpaper
  copy:
    src: "{{ theme_dir }}/wallpaper.jpg"
    dest: "/home/{{ username }}/.local/share/bg"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Create i3 config directory
  directory:
    path: "/home/{{ username }}/.config/i3"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Configure i3
  template:
    src: files/i3-config
    dest: "/home/{{ username }}/.config/i3/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Create picom config directory
  directory:
    path: "/home/{{ username }}/.config/pipcom"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Configure picom
  template:
    src: files/picom.conf
    dest: "/home/{{ username }}/.config/picom/picom.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Create polybar config directory
  directory:
    path: "/home/{{ username }}/.config/polybar"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Copy polybar config
  template:
    src: files/polybar/config.ini
    dest: "/home/{{ username }}/.config/polybar/config.ini"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy polybar launcher
  template:
    src: files/polybar/launch.sh
    dest: "/home/{{ username }}/.config/polybar/launch.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create autorandr config directory
  directory:
    path: "/home/{{ username }}/.config/autorandr"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Configure autorandr postswitch script
  copy:
    src: files/autorandr/postswitch
    dest: "/home/{{ username }}/.config/autorandr/postswitch"
    owner: "{{ username }}"
    group: "{{ username}}"
    mode: 0755

- name: Copy background script
  copy:
    src: files/setbg
    dest: /usr/local/bin/setbg
    mode: 0755
