- name: Install NetworkManager, openvpn and other helpers
  pacman:
    packages:
    - networkmanager
    - network-manager-applet
    - nm-connection-editor
    - openvpn
    - networkmanager-openvpn
    - networkmanager-l2tp
    - strongswan
    - iw

- name: Start NetworkManager service
  service:
    service: NetworkManager
    started: yes
    enabled: yes

- name: Make NetworkManager use iwd
  copy:
    src: files/network-manager/wifi_backend.conf
    dest: /etc/NetworkManager/conf.d/wifi_backend.conf


- name: Configure iwlwifi
  copy:
    content: options iwlwifi wd_disable=1
    dest: /etc/modprobe.d/iwlwifi.conf
