- name: Install dev tools
  pacman:
    packages:
    - man-db
    - bat
    - tree
    - nano
    - screenfetch
    - flameshot
    - rsync
    - nmap
    - httpie
    - jq
    - wget
    - curl
    - lsof
    - postgresql
    - usbutils
    - the_silver_searcher
    - pciutils
    - bind
    - ffmpeg
    - imagemagick
    - dmenu
    - mediainfo
    - cronie
    - perl-image-exiftool
    - youtube-dl
    - binutils
    - xclip
    - zip
    - unzip
    - blueman
    - redis
    - xdotool

- name: Install dev tools (AUR)
  aur:
    packages:
    - duf
    - git-delta
    - bottom
  become: makepkg

- name: Enable cronie service
  service:
    service: cronie
    started: yes
    enabled: yes
