- name: Install dev tools
  pacman:
    packages:
    - man-db
    - bat
    - tree
    - nano
    - screenfetch
    - flameshot
    - rsync
    - nmap
    - httpie
    - jq
    - wget
    - curl
    - lsof
    - postgresql
    - usbutils
    - the_silver_searcher
    - pciutils
    - bind
    - ffmpeg
    - imagemagick
    - dmenu
    - mediainfo
    - cronie
    - perl-image-exiftool
    - youtube-dl
    - binutils
    - xclip
    - zip
    - unzip
    - blueman
    - redis
    - xdotool
    - screen
    - namcap
    - thefuck
    - docker
    - pgcli
    - fd
    - terraform
    - certbot
    - z

- name: Add primary user to docker group
  user:
    user: "{{ username }}"
    groups: docker

- name: Install dev tools (AUR)
  aur:
    packages:
    - duf
    - git-delta
    - bottom
    - aws-cdk
    - heroku-cli

- name: Enable cronie service
  service:
    service: cronie
    started: yes
    enabled: yes
