- name: Create primary user
  user:
    user: "{{ username }}"
    create_home: true
    shell: /usr/bin/zsh
    groups: sudo
    password: "{{ login_password | password_hash('sha512') }}"
  when: login_password is defined

- name: Create .config directory
  directory:
    path: "/home/{{ username }}/.config"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755
