- name: Install Xorg
  pacman:
    packages:
    - xorg-server
    - xorg-xinit
    - xorg-xrdb

- name: Install Xorg tools
  pacman:
    packages:
    - xorg-xmodmap
    - xorg-xrandr
    - xorg-xev
    - xorg-xset
    - xorg-xinput
    - "{{ kernel }}-headers"

- name: Install VirtualBox Xorg driver
  pacman:
    packages:
    - xf86-video-vmware
    - virtualbox-guest-utils
    - "{{ kernel }}-headers"
  when: model == "virtualbox"

- name: Enable vboxservice
  service:
    service: vboxservice
    started: yes
    enabled: yes
  when: model == "virtualbox"

- name: Install Dell XPS 7590 graphics packages
  pacman:
    packages: xf86-video-intel
  when: model == "dell-xps-7590"
