- name: Install base-devel and git
  pacman:
    packages:
    - base-devel
    - git

- name: Create makepkg user
  user:
    user: makepkg
    create_home: yes
    system: yes

- name: Install yay
  aur:
    packages: yay
  become: makepkg
