- name: Install alacritty
  pacman:
    packages: alacritty

- name: Create alacritty config directory
  directory:
    path: "/home/{{ username }}/.config/alacritty"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Copy alacritty config
  template:
    src: files/alacritty.yml
    dest: "/home/{{ username }}/.config/alacritty/alacritty.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
