- name: Install neovim
  pacman:
    packages:
    - neovim
    - python-pynvim

- name: Install terraform language server
  aur:
    packages:
    - terraform-ls

- name: Create neovim config directory
  directory:
    path: "/home/{{ username }}/.config/nvim"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Copy neovim init.vim
  copy:
    src: files/nvim/init.vim
    dest: "/home/{{ username }}/.config/nvim/init.vim"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Create vim plug directory
  directory:
    path: "/home/{{ username }}/.local/share/nvim/site/autoload/"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755

- name: Install vim plug
  copy:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ username }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0644

- name: Configure vim coc
  copy:
    src: files/nvim/coc-settings.json
    dest: "/home/{{ username }}/.config/nvim/coc-settings.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
