# https://github.com/alacritty/alacritty/issues/3652
[[keyboard.bindings]]
chars = "\u007F"
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[scrolling]
history = 10000

[env]
TERM = "xterm-256color"

{% include theme_dir + "alacritty" %}
